version: '3'

networks:
  laravel:

services:
    nginx:
        image: library/nginx:stable-alpine
        container_name: nginx
        volumes:
            - ./src/app:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports :
            - "8060:80"           
        depends_on:
            - php
            - mysql
        networks :
            - laravel

    mysql:
        image: library/mysql:5.7.22
        container_name: mysql
        restart: unless-stopped
        ports :
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: task
            MYSQL_USER: root
            MYSQL_PASSWORD : root
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGs: dev
            SERVICE_NAME: mysql
        networks :
            - laravel

    mysql_test:
        image: library/mysql:5.7.22
        container_name: mysql_test
        restart: unless-stopped
        ports :
            - "3307:3306"
        volumes:
            - ./mysql_test:/var/lib/mysql
        environment:
            MYSQL_DATABASE: task_test
            MYSQL_USER: root
            MYSQL_PASSWORD : root
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGs: dev
            SERVICE_NAME: mysql_test
        networks :
            - laravel
            
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes:
            - ./src/app:/var/www/html
        ports :
            - "9000:9000"
        networks :
            - laravel
        command: >
            sh -c "composer install &&
                    cp .env.example .env &&
                    php artisan key:generate &&
                    php artisan migrate:fresh --seed &&
                    php artisan jwt:secret &&
                    php-fpm"